import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      // Common
      'app_name': 'Paysheet App',
      'app_title': 'Paysheet Management',
      'professional_paysheet_management': 'Professional Paysheet Management',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'filter': 'Filter',
      'from_date': 'From Date',
      'to_date': 'To Date',
      'apply_filter': 'Apply Filter',
      'clear_filter': 'Clear Filter',
      'no_data': 'No data available',
      'session_expired': 'Session expired. Please login again.',
      'close': 'Close',
      'next': 'Next',
      'previous': 'Previous',
      'refresh': 'Refresh',

      // Auth
      'login': 'Login',
      'logout': 'Logout',
      'username': 'Username',
      'email_or_username': 'Email or Username',
      'password': 'Password',
      'sign_in': 'Sign In',
      'login_failed': 'Login failed',
      'unknown_user_type': 'Unknown user type',
      'authentication_token_not_found': 'Authentication token not found',

      // Dashboard
      'dashboard': 'Dashboard',
      'total_bills': 'Total Bills',
      'total_payments': 'Total Payments',
      'total_amount': 'Total Amount',
      'paid_amount': 'Paid Amount',
      'pending_amount': 'Pending Amount',
      'total_returns': 'Total Returns',
      'total_bill_amount': 'Total Bill Amount',
      'total_payment_amount': 'Total Payment Amount',
      'total_return_amount': 'Total Return Amount',
      'net_amount': 'Net Amount',
      'financial_summary': 'Financial Summary',
      'your_financial_overview': 'Your financial overview',
      'positive': 'Positive',
      'negative': 'Negative',
      'balance': 'Balance',
      'updated': 'Updated',

      // Bills
      'bills': 'Bills',
      'my_bills': 'My Bills',
      'bill_id': 'Bill ID',
      'bill_date': 'Bill Date',
      'amount': 'Amount',
      'description': 'Description',
      'status': 'Status',
      'no_bills_found': 'No bills found',

      // Payments
      'payments': 'Payments',
      'my_payments': 'My Payments',
      'payment_id': 'Payment ID',
      'payment_date': 'Payment Date',
      'payment_method': 'Payment Method',
      'cash': 'Cash',
      'bank_transfer': 'Bank Transfer',
      'bank': 'Bank',
      'credit_card': 'Credit Card',
      'pos': 'POS',
      'cheque': 'Cheque',
      'no_payments_found': 'No payments found',

      // Returns
      'returns': 'Returns',
      'my_returns': 'My Returns',
      'return_id': 'Return ID',
      'return_date': 'Return Date',
      'reason': 'Reason',
      'no_returns_found': 'No returns found',

      // Customer Management (Owner)
      'customers': 'Customers',
      'no_customers_found': 'No customers found',
      'create_your_first_customer': 'Create your first customer to get started',
      'new_customer': 'New Customer',
      'create_new_customer': 'Create New Customer',
      'customer_id': 'Customer ID',
      'customer_id_required': 'Customer ID is required',
      'customer_id_hint': 'Enter customer ID (e.g., CUST001)',
      'phone_number': 'Phone Number',
      'phone_number_required': 'Phone number is required',
      'phone_number_hint': 'Enter phone number',
      'password_required': 'Password is required',
      'shop_name': 'Shop Name',
      'shop_name_required': 'Shop name is required',
      'shop_name_hint': 'Enter shop name',
      'vat_number': 'VAT Number',
      'vat_number_hint': 'Enter VAT number (optional)',
      'description_hint': 'Enter description (optional)',
      'create_customer': 'Create Customer',
      'customer_created_successfully': 'Customer created successfully',
      'customer_id_already_exists': 'Customer ID already exists',
      'failed_to_create_customer': 'Failed to create customer',
      'failed_to_load_customers': 'Failed to load customers',
      'search_customers': 'Search customers...',

      // Date Selection
      'select_from_date': 'Select from date',
      'select_to_date': 'Select to date',

      // Settings
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'arabic': 'العربية',
      'change_language': 'Change Language',
      'profile': 'Profile',
      'ok': 'OK',
      'business_settings': 'Business Settings',
      'security': 'Security',
      'company_information': 'Company Information',
      'customer_management': 'Customer Management',
      'reports_analytics': 'Reports & Analytics',
      'change_password': 'Change Password',
      'two_factor_auth': 'Two-Factor Authentication',
      'coming_soon': 'Coming Soon',
      'coming_soon_message':
          'This feature will be available in a future update.',

      // Messages
      'data_loaded_successfully': 'Data loaded successfully',
      'filter_applied': 'Filter applied',
      'language_changed': 'Language changed successfully',
      'bad_request': 'Bad request',

      // Form Validation
      'required_field': 'This field is required',
      'invalid_input': 'Invalid input',

      // Status
      'pending': 'Pending',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'processed': 'Processed',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'active': 'Active',
      'inactive': 'Inactive',

      // Currency
      'currency_symbol': '\$',
      'currency_format': '{symbol}{amount}',

      // Additional Financial Terms
      'summary': 'Summary',
      'overview': 'Overview',
      'financial_data': 'Financial Data',
      'amount_details': 'Amount Details',
      'about': 'About',
      'financial_report': 'Financial Report',
      'transaction_summary': 'Transaction Summary',
      'account_balance': 'Account Balance',
      'credit': 'Credit',
      'debit': 'Debit',
    },
    'ar_SA': {
      // Common
      'app_name': 'تطبيق كشف الراتب',
      'app_title': 'إدارة كشف الراتب',
      'professional_paysheet_management': 'إدارة كشف الراتب المهنية',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجح',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'add': 'إضافة',
      'search': 'بحث',
      'filter': 'تصفية',
      'from_date': 'من تاريخ',
      'to_date': 'إلى تاريخ',
      'apply_filter': 'تطبيق التصفية',
      'clear_filter': 'مسح التصفية',
      'no_data': 'لا توجد بيانات متاحة',
      'session_expired': 'انتهت الجلسة. يرجى تسجيل الدخول مرة أخرى.',
      'close': 'إغلاق',
      'next': 'التالي',
      'previous': 'السابق',
      'refresh': 'تحديث',

      // Auth
      'login': 'تسجيل الدخول',
      'logout': 'تسجيل الخروج',
      'username': 'اسم المستخدم',
      'email_or_username': 'البريد الإلكتروني أو اسم المستخدم',
      'password': 'كلمة المرور',
      'sign_in': 'تسجيل الدخول',
      'login_failed': 'فشل في تسجيل الدخول',
      'unknown_user_type': 'نوع مستخدم غير معروف',
      'authentication_token_not_found': 'رمز المصادقة غير موجود',

      // Dashboard
      'dashboard': 'لوحة التحكم',
      'total_bills': 'إجمالي الفواتير',
      'total_payments': 'إجمالي المدفوعات',
      'total_amount': 'المبلغ الإجمالي',
      'paid_amount': 'المبلغ المدفوع',
      'pending_amount': 'المبلغ المعلق',
      'total_returns': 'إجمالي المرتجعات',
      'total_bill_amount': 'إجمالي مبلغ الفواتير',
      'total_payment_amount': 'إجمالي مبلغ المدفوعات',
      'total_return_amount': 'إجمالي مبلغ المرتجعات',
      'net_amount': 'صافي المبلغ',
      'financial_summary': 'الملخص المالي',
      'your_financial_overview': 'نظرة عامة على أموالك',
      'positive': 'إيجابي',
      'negative': 'سلبي',
      'balance': 'الرصيد',
      'updated': 'محدث',

      // Bills
      'bills': 'الفواتير',
      'my_bills': 'فواتيري',
      'bill_id': 'رقم الفاتورة',
      'bill_date': 'تاريخ الفاتورة',
      'amount': 'المبلغ',
      'description': 'الوصف',
      'status': 'الحالة',
      'no_bills_found': 'لم يتم العثور على فواتير',

      // Payments
      'payments': 'المدفوعات',
      'my_payments': 'مدفوعاتي',
      'payment_id': 'رقم الدفع',
      'payment_date': 'تاريخ الدفع',
      'payment_method': 'طريقة الدفع',
      'cash': 'نقداً',
      'bank_transfer': 'تحويل بنكي',
      'bank': 'بنك',
      'credit_card': 'بطاقة ائتمان',
      'pos': 'نقاط البيع',
      'cheque': 'شيك',
      'no_payments_found': 'لم يتم العثور على مدفوعات',

      // Returns
      'returns': 'المرتجعات',
      'my_returns': 'مرتجعاتي',
      'return_id': 'رقم المرتجع',
      'return_date': 'تاريخ الإرجاع',
      'reason': 'السبب',
      'no_returns_found': 'لم يتم العثور على مرتجعات',

      // Customer Management (Owner)
      'customers': 'العملاء',
      'no_customers_found': 'لم يتم العثور على عملاء',
      'create_your_first_customer': 'أنشئ عميلك الأول للبدء',
      'new_customer': 'عميل جديد',
      'create_new_customer': 'إنشاء عميل جديد',
      'customer_id': 'رقم العميل',
      'customer_id_required': 'رقم العميل مطلوب',
      'customer_id_hint': 'أدخل رقم العميل (مثال: CUST001)',
      'phone_number': 'رقم الهاتف',
      'phone_number_required': 'رقم الهاتف مطلوب',
      'phone_number_hint': 'أدخل رقم الهاتف',
      'password_required': 'كلمة المرور مطلوبة',
      'shop_name': 'اسم المتجر',
      'shop_name_required': 'اسم المتجر مطلوب',
      'shop_name_hint': 'أدخل اسم المتجر',
      'vat_number': 'رقم ضريبة القيمة المضافة',
      'vat_number_hint': 'أدخل رقم ضريبة القيمة المضافة (اختياري)',
      'description_hint': 'أدخل الوصف (اختياري)',
      'create_customer': 'إنشاء عميل',
      'customer_created_successfully': 'تم إنشاء العميل بنجاح',
      'customer_id_already_exists': 'رقم العميل موجود بالفعل',
      'failed_to_create_customer': 'فشل في إنشاء العميل',
      'failed_to_load_customers': 'فشل في تحميل العملاء',
      'search_customers': 'البحث عن العملاء...',

      // Date Selection
      'select_from_date': 'اختر من تاريخ',
      'select_to_date': 'اختر إلى تاريخ',

      // Settings
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'english': 'English',
      'arabic': 'العربية',
      'change_language': 'تغيير اللغة',
      'profile': 'الملف الشخصي',
      'ok': 'موافق',
      'business_settings': 'إعدادات الأعمال',
      'security': 'الأمان',
      'company_information': 'معلومات الشركة',
      'customer_management': 'إدارة العملاء',
      'reports_analytics': 'التقارير والتحليلات',
      'change_password': 'تغيير كلمة المرور',
      'two_factor_auth': 'المصادقة الثنائية',
      'coming_soon': 'قريباً',
      'coming_soon_message': 'ستكون هذه الميزة متاحة في تحديث مستقبلي.',

      // Messages
      'data_loaded_successfully': 'تم تحميل البيانات بنجاح',
      'filter_applied': 'تم تطبيق التصفية',
      'language_changed': 'تم تغيير اللغة بنجاح',
      'bad_request': 'طلب خاطئ',

      // Form Validation
      'required_field': 'هذا الحقل مطلوب',
      'invalid_input': 'إدخال غير صحيح',

      // Status
      'pending': 'قيد الانتظار',
      'approved': 'موافق عليه',
      'rejected': 'مرفوض',
      'processed': 'تمت معالجته',
      'completed': 'مكتمل',
      'cancelled': 'ملغي',
      'active': 'نشط',
      'inactive': 'غير نشط',

      // Currency
      'currency_symbol': 'ر.س',
      'currency_format': '{amount} {symbol}',

      // Additional Financial Terms
      'summary': 'الملخص',
      'overview': 'نظرة عامة',
      'financial_data': 'البيانات المالية',
      'amount_details': 'تفاصيل المبلغ',
      'about': 'حول',
      'financial_report': 'التقرير المالي',
      'transaction_summary': 'ملخص المعاملات',
      'account_balance': 'رصيد الحساب',
      'credit': 'دائن',
      'debit': 'مدين',
    },
  };
}
